### ISSUE TITLE
Rename Diagnosis Button is Incorrectly Titled "Change Medication"

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#1001]
The Rename Diagnosis button has the title set to "Change medication", when it should probably be "Change diagnosis"

![rename_diagnosis_link_title](https://user-images.githubusercontent.com/6118864/30948293-44740be8-a452-11e7-8dad-23f90f113e1a.png)

**Comment by biskyt** [comment]
Nice spot. Thanks. Just merged in
