### ISSUE TITLE
Application Error Occurs when User Edits "Therapy Application Sender Email"

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#1008]
If the user attempts to ed it the "Therapy Application Sender Email" metadata setting, then an application error occurs because the setting has the field type of 3 (radio button) when it should have the field type of 4 (text field)

**Comment by marshl** [comment]
Relates to https://github.com/FiviumAustralia/OpenEyes/pull/190

**Comment by biskyt** [comment]
Fixed in commit f7c6586de68aac54d7eb7aa3be4a8615c523c217 (https://github.com/openeyes/OpenEyes/commit/f7c6586de68aac54d7eb7aa3be4a8615c523c217).

Used a new migration as some customers are now using v2.0 release candidate
