### ISSUE TITLE
trainning and e-learning

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#117]
I cant find the documentation or guide and e-learning portal that i found about in http://www.openeyes.org.uk/support-training/e-learning/
I have sent an e-mail but no replay

**Comment by petergallagher** [comment]
Hello,

The e-learning portal is available at http://elearning.openeyes.org.uk/. Currently the documentation is in transition as we try to tidy things up but what exists can be found on the Wiki of this github page

**Comment by farissalih87** [comment]
thank you very much

**Comment by petergallagher** [comment]
No problem, I'll close this issue now.
