### ISSUE TITLE
cant install OphCiExamination

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#119]
Iam trying to install the OphCiExamination module 
after copy the module directory to  protected/modules 
and add it to the array in common.php
i cant find it in the events list

**Comment by MassimoDanieli** [comment]
Hi

did you run the migration script ?

cd /var/www/openeyes/protected/modules

./yiic migratemodules

Cheers

Massimo

**Comment by farissalih87** [comment]
no iam doing this in windows with xampp localserver

**Comment by farissalih87** [comment]
iam new to this i did the AddPatiant module successfully and i need the eyedraw and the examenation

**Comment by petergallagher** [comment]
Hi,

If you are just looking to get OpenEyes up and running locally I would recommend right now checking out the develop branch as we have made some improvements to the install process there. Although they have not been released they do greatly increase the ease with which you can get OpenEyes running.

I would recommend installing VirtualBox and Vagrant, if you install these then checkout develop, running `vagrant up` inside the root folder should set up a virtual machine for you and install all the modules you require using composer. You will then only need to import the sample data if you require that.

Peter

**Comment by farissalih87** [comment]
i will try the develop branch
but i didn't  understand the other way ((VirtualBox and Vagrant))

**Comment by farissalih87** [comment]
you mean whith Ubuntu and folow the normal installation guide  ?

**Comment by farissalih87** [comment]
sorry 

but i cant find the .git link to develop bransh  so i can clone it uesing git bash
one moer thing 
if i used the develop bransh no need to migrate ????

**Comment by petergallagher** [comment]
To get the develop branch you just clone the URL on the github page and then run `git checkout develop`. I've now updated the docs on the wiki so if you follow these steps it should work fine https://github.com/openeyes/OpenEyes/wiki/Quick-Start-with-Vagrant

**Comment by farissalih87** [comment]
solved thank you :)
