### ISSUE TITLE
white page no login 

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#156]
after installation of develop branch in ubuntu desktop 15.0.4  iam getting  a clear white page no login page   no errors ????

**Comment by farissalih87** [comment]
changed every thing to ubuntu server and master branch  but still have the same problem

**Comment by petergallagher** [comment]
It sounds like there is a PHP error or exception that isn't being displayed, you'll need to configure your PHP installation to show them.

**Comment by farissalih87** [comment]
thank you for the fast answer i was thinking about that but how??

**Comment by farissalih87** [comment]
found the php.ini and set all type of error reporting to on 
still cant see any errors

**Comment by petergallagher** [comment]
Sounds like display_errors wasn't set, or the issue may be with apache instead, or possibly the web server just needs restarting.

**Comment by farissalih87** [comment]
you were wright 
I found two display_error parameters
 now i can see 

Warning: require_once(/var/www/openeyes/vendor/yiisoft/yii/framework/yii.php): failed to open stream: No such file or directory in /var/www/openeyes/index.php on line 43

Fatal error: require_once(): Failed opening required '/var/www/openeyes/vendor/yiisoft/yii/framework/yii.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/openeyes/index.php on line 43

but i have installed yii using 


Initialise the yii framework:

# cd /var/www/openeyes
# git submodule init
# git submodule update

**Comment by farissalih87** [comment]
worked  after editing the index.php 
by changing
/vendor/yiisoft/yii/framework/yii.php  to /protected/yii/framework/yii.php
but i cant see any of the installed modules
and get nothing when running 
/yiic migratemodules

**Comment by petergallagher** [comment]
We recently changed how Yii and the modules are installed in the project, so instead of submodules you will need to install composer and run `composer install` in the root of the project. Can you let me know which documentation you are following so I can update it?

**Comment by farissalih87** [comment]
Iam following the one in the wiki 
openeyes installation guide 
https://github.com/openeyes/OpenEyes/wiki/OpenEyes-Installation
and Can you tell me which one is updated so i can follow??

**Comment by farissalih87** [comment]
composer install  solved some of the problems but the most of it solved after running the ./yiic migration again ..
but still cant git the eyedraw and addpatient working

**Comment by farissalih87** [comment]
solved it was internet connection issue
