### ISSUE TITLE
full updated installation guide pleae

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#159]
cant find any installation guide in the openeyes website and you told me that you have changed the way of installing the project and the modules
I have tried the composer install way but I cant pass the (zendframework/zend-stdlib)
its telling me remote invalid  username or password  
- I can see the login and login but I cant git the eyedraw and the addpatient modules working
I spent one month trying to do this please help 
Note: Iam installing this on HP ML310e server with Ubuntu Serve 14.04

**Comment by antonypenn** [comment]
Hi,
Clone the oe_installer repo on to your target machine, then run:
installer-system.sh and installer-oe.sh

**Comment by hurley27** [comment]
hi. i have done  all of this but the add patient module is absent from the latest versin and i see nothing there in the repo. should i downgrade my version?
