### ISSUE TITLE
new user and change password error

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#162]
I am gitting this error 

*****************************************
CException

Property "User.password_old" is not defined.

/var/www/openeyes/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(145)
******************************************
when try to change the admin password
and cant use the new created users account

**Comment by antonypenn** [comment]
It sounds like the database migrations have not been run.
cd /var/www/protected
./yiic migrate --interactive=0
./yiic migratemodules --interactive=0
