### ISSUE TITLE
Reports and Ultrasound Modules

### ISSUE THREAD

**Issue by farissalih87** [openeyes/OpenEyes#166]
1- I have installed the Reports Module and did the migration successfully 
but I dont know where to find it.
2- placed the ultrasound folder and added to he common.php I can see the link from the Events list but its not working.

Please help me iam stopping here 3 months

**Comment by farissalih87** [comment]
any thing regarding this????

**Comment by antonypenn** [comment]
The code layout has changed significantly since this time.
I suggest you re-install from scratch.
Go to the oe_installer module and follow the instructions from there.
