### ISSUE TITLE
The table "patientticketing_queuesetcategory" for active record class "OEModule\PatientTicketing\models\QueueSetCategory" cannot be found in the database.

### ISSUE THREAD

**Issue by iceict** [openeyes/OpenEyes#175]
Hi 

I cant seem to get the table "patientticketing_queuesetcategory" created.
I am not sure what I am doing wrong.

As far as I can see the modules are all there.
I have done composer installation and .yiic migrate/migratemodule.

But there still seems to be tables missing.

Any suggestions?

Cheers
Andreas

**Comment by pgwanZ** [comment]
Which release are you attempting to install, and can you outline the steps that you have taken?

**Comment by iceict** [comment]
Hi

Well hopefully it’s the latest version.
These are the steps I am doing.

Step by step
Root directory named op1

1. Downloaded/Installed Git Bash and Composer
2. Create database
3. Import data from "openeyes+ophtroperationbooking.sql"

4. Loaded Git Bash and type the following into the Git Bash window
Typed: git clone https://github.com/openeyes/OpenEyes.git c:/xampp/htdocs/op1

5. Initialise the Yii framework
Typed: cd c:/xampp/htdocs/op1
Typed: git submodule init
Typed: git submodule update

6. Renamed index.example.php to index.php

7. Edited index.php
Changed line 21
$yii = $dirname . '/vendor/yiisoft/yii/framework/yii.php';
to
$yii = $dirname . '/protected/yii/framework/yii.php';

8. Renamed .htaccess.sample to .htaccess
9. Renamed folder local.sample to local in protected\config
10. Renamed common.sample.php to common.php in protected\config\local

11. Edited common.php
Line 23-25: Updated database name, username and password
Line 111: Updated "live" to "dev"

12. Created a runtime folder in protected folder
****
At this point I can login using Admin/Admin
But many tables are missing example like the "patient_risk_assignment" table
So next step I do the following
****

13. Using Windows CMD root directory of openeyes (C:\xampp\htdocs\op1)
Typed composer install --no-dev
When CMD says Generating autoload files I can see its done

14. Open git bach and navigate to protected folder
Typed: ./yiic migrate
When asked if I want Apply the above migrations I say YES
When "Migrated up successfully" is shown in Git Bash I type
Typed: ./yiic migratemodules
Apply the above migrations? (yes|no) [no]: Y
I continue to say YES when Git Bash askes
Exit GIT BASH

****
Many new tables been created including the "patient_risk_assignment" table

But now when I login I get the following error
The table "patientticketing_queuesetcategory" for active record class "OEModule\PatientTicketing\models\QueueSetCategory" cannot be found in the database.


This is the steps I did but I can’t seem to get any further than this. ☹

Kind regards
Andreas


Andreas Sivermark
ICE-ICT
[Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Logo no puddle sml][Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ICE MS Sliver partner logo]

Central London: 23 Austin Friars, London, EC2N 2QP
Main Office: BioPark, Broadwater Road, Welwyn Garden City
Hertfordshire AL7 3AX - United Kingdom
______________________________________
ICE Support email: icehelpdesk@iceict.net<mailto:icehelpdesk@iceict.net>
ICE UK Servicedesk +44 3333 4444 66
Fax: +44 20 3322 6909

Email: as@iceict.net<mailto:as@iceict.net>
Web: www.iceict.net<http://www.iceict.net/>
Skype: Andreas_ICESupport
[skype]<skype:%20Andreas_ICESupport?add>

**Comment by iceict** [comment]
Any ideas how I can proceed and get this working?

**Comment by iceict** [comment]
I got alot further doing this
1. In the browser go to https://github.com/openeyes/Sample and copy the clone URL
2. git clone https://github.com/openeyes/Sample.git
3. cd Sample/sql
4. git checkout release/v1.11
5. import data to my database.

I now don't have any table issues anymore. :)
I do have some issues with root directory (referring page) since I have one extra folder.

So for an example if I search and it want to return an error it link me to the wrong URL.

Example :
instead of going to
http://oetest/openeyes/search
it will go to
http://oetest/search

But just have to find that (referring page) configuration some place. 
But hopefully this should not be a problem finding. 

Cheers
Andreas

**Comment by andakh876** [comment]
I have the same issue as Andreas.  When I search it goes to folder above the application folder.
Is the a fix for this?
