### ISSUE TITLE
Two lefts in the injection report post-injection VA

### ISSUE THREAD

**Issue by RupW** [openeyes/OpenEyes#419]
A trivial one, spotted in passing: in the intravitreal injection module you're reporting the left post-injection visual acuity twice, rather than left and right:

					<?php if ($report->post_va) {?>
						<td><?php echo $injection['left_postinjection_va']?></td>
						<td><?php echo $injection['left_postinjection_va']?></td>
					<?php }?>

https://github.com/openeyes/OpenEyes/blob/v1.15.1/protected/modules/OphTrIntravitrealinjection/views/report/_injections.php#L80

**Comment by mikepargeter** [comment]
Thank you, this has been fixed for the next release.
