### ISSUE TITLE
Title text for non-mandatory remove element buttons set to "1"

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#668]
The title text for the remove buttons on elements that cannot be removed from the screen is set to "mandatory", but is set to "1" if the element can be removed. I think this may be a bug.

The cursor is not shown in this image, but the title text is circled in red:
![openeyes_2017_24_02_remove_element_title_text](https://cloud.githubusercontent.com/assets/6118864/23290291/cc882004-faa3-11e6-9b94-001b6eb188b1.png)

**Comment by marshl** [comment]
The code in question (/protected/views/patient/element_container_form.php 80:90) seems to be incorrectly using the null-coalesce version of the conditional operator to determine the title text. I can push a fix, but I'm not sure about your procedures.

**Comment by mikepargeter** [comment]
Many thanks Liam. I'm not sure of our procedures either! Can you push onto our develop branch? Then I can test and include in the next release.

**Comment by mikepargeter** [comment]
Many thanks, looks good here.
