### ISSUE TITLE
Vagrant Up Failing due to Table DNE Exception

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#796]
When I was trying to vagrant up the feature/genetics branch of OpenEyes, I encountered an exception during migration of the m170316_123900_remove_investigator_table_and_dnatests_transaction_add_comments_field patch. The exception occurred because the ophindnaextraction_dnatests_transaction table did not exist at the time. It seems to be created in /protected/modules/OphInDnaextraction/m131115_142803_dna_tests_element.php

Is m170316_123900 meant to be located in the OphInDnaextraction module instead of the core protected folder?

Here is the full message:
```
 "*** applying m170316_123900_remove_investigator_table_and_dnatests_transaction_add_comments_field", "    > drop foreign key ophindnaextraction_dnatests_transaction_inv_fk from table ophindnaextraction_dnatests_transaction ...exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'openeyes.ophindnaextraction_dnatests_transaction' doesn't exist. The SQL statement executed was: ALTER TABLE `ophindnaextraction_dnatests_transaction` DROP FOREIGN KEY `ophindnaextraction_dnatests_transaction_inv_fk`'
```

**Comment by marshl** [comment]
I had a similar issue with the protected\migrations\m170320_201259_remove_external_source.php file as well

**Comment by mikepargeter** [comment]
Thanks for letting us know, I've made a commit on feature/genetics to put these migrations in the right place.
