### ISSUE TITLE
"Username has already been taken" Validation Error Occurs when Updating a User

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#940]
If an admin user updates any fields in the Edit Patient screen, then a validation error prevents the user from being saved because the username is used by an existing record (the existing record being the user that is being edited).
![image](https://user-images.githubusercontent.com/6118864/29444228-2bf4149c-8421-11e7-8381-64f411aef329.png)

**Comment by biskyt** [comment]
Having trouble replicating this. Could you please provide precise steps? Using latest develop branch

**Comment by marshl** [comment]
I can only replicate this with the users that come shipped in the sample data. I can't replicate it with new users.
To replicate with sample data, I just vagrant up'd from develop, went into the user edit screen for Jing Straw (username: Straw) and attempted to save without changing any fields.

**Comment by marshl** [comment]
Oh, I see. The "issue" was caused by the fact that the sample data has multiple users with the same username. Sorry about that, I'll close the issue and PR
