### ISSUE TITLE
Application Error when all Roles are Removed from User

### ISSUE THREAD

**Issue by marshl** [openeyes/OpenEyes#946]
If all roles are removed from a User via the admin console, then an application error occurs when the user record is validated.

**Comment by marshl** [comment]
[app_error_no_roles.txt](https://github.com/openeyes/OpenEyes/files/1237493/app_error_no_roles.txt)

**Comment by marshl** [comment]
![image](https://user-images.githubusercontent.com/6118864/29500032-ec5b933c-865f-11e7-844b-92cb5938f146.png)

**Comment by marshl** [comment]
![image](https://user-images.githubusercontent.com/6118864/29500047-171f90be-8660-11e7-8025-b2c3254a3a38.png)

**Comment by biskyt** [comment]
@marshl - Is this still an issue for you in V2.0? I'm unable to replicate

**Comment by marshl** [comment]
@biskyt I concur, this longer appears to be an issue in release/v2.0
